### ISSUE TITLE
bigtable: Error when running "cbt count"

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#659]
When I run the `cbt count <tablename>` command, I consistently get the following error message:

```
2017/06/12 16:32:40 Retryable error: rpc error: code = Unavailable desc = grpc: the connection is closing, retrying in 47.77941ms
```

The error message is followed by the number of lines in the table, so the command works—it just complains first.

I'm using the `cbt` tool that's packaged with the Cloud SDK (`cbt 0.2.0 dca61c4 2017-05-08 22:20:04`) on macOS Sierra 10.12.5.

**Comment by garye** [comment]
How long does the command run for? Does the line count get printed immediately after the error?

**Comment by hegemonic** [comment]
The error message is printed almost instantly, and the line count is printed about half a second later. (I'm running `cbt count` against extremely small tables.)

**Comment by spark2ignite** [comment]
+1

**Comment by stiancognite** [comment]
I'm also seeing this error. And it says that it's gong to retry in 47.77941ms but it just hangs. I have to close the shell to get out of it.
```
➜  cbt version
2017/10/30 07:44:22 proto: duplicate proto type registered: google.rpc.Status
0.2.2 7d132fe 2017-06-09 14:30:04
```
Installed with `gcloud components install cbt`.

**Comment by anthmgoogle** [comment]
This repository is for the google-cloud-go client library. Can you create this bug in the repository for the Cloud SDK where this issue lives?

**Comment by anthmgoogle** [comment]
Apologies. Reactivated.

**Comment by garye** [comment]
We're working through some internal release issues to get this fixed in the
cloud SDK. If you build cbt from source in this repository it should work
fine.

**Comment by hegemonic** [comment]
Thanks for clarifying, @garye! In light of that, it's fine with me to close this bug.

**Comment by Martin-Narvar** [comment]
This is a pretty old thread, but this appears to be still a problem in 2025
